[2023-05-07T15:55:04.629-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bigdata_tp.TopCTR manual__2023-05-07T18:54:54.815310+00:00 [queued]>
[2023-05-07T15:55:04.640-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bigdata_tp.TopCTR manual__2023-05-07T18:54:54.815310+00:00 [queued]>
[2023-05-07T15:55:04.640-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T15:55:04.641-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-07T15:55:04.641-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T15:55:04.659-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): TopCTR> on 2023-05-07 18:54:54.815310+00:00
[2023-05-07T15:55:04.680-0300] {standard_task_runner.py:55} INFO - Started process 2080 to run task
[2023-05-07T15:55:04.692-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'bigdata_tp', 'TopCTR', 'manual__2023-05-07T18:54:54.815310+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1lpdt9io']
[2023-05-07T15:55:04.697-0300] {standard_task_runner.py:83} INFO - Job 64: Subtask TopCTR
[2023-05-07T15:55:04.777-0300] {task_command.py:389} INFO - Running <TaskInstance: bigdata_tp.TopCTR manual__2023-05-07T18:54:54.815310+00:00 [running]> on host DESKTOP-02TA80M.localdomain
[2023-05-07T15:55:04.849-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bigdata_tp
AIRFLOW_CTX_TASK_ID=TopCTR
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T18:54:54.815310+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-07T18:54:54.815310+00:00
[2023-05-07T15:55:04.930-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alanmatys/airflow/dags/dag.py", line 47, in TopCTR
    ads_views['success'] = df["event"].apply(lambda x: 1 if x == "click" else 0)
NameError: name 'df' is not defined
[2023-05-07T15:55:04.938-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=bigdata_tp, task_id=TopCTR, execution_date=20230507T185454, start_date=20230507T185504, end_date=20230507T185504
[2023-05-07T15:55:04.953-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 64 for task TopCTR (name 'df' is not defined; 2080)
[2023-05-07T15:55:04.983-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-07T15:55:05.005-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
