[2023-05-02T22:10:51.746-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bigdata_tp.FiltrarDatos scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-02T22:10:51.770-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bigdata_tp.FiltrarDatos scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-02T22:10:51.771-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T22:10:51.771-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T22:10:51.772-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T22:10:51.838-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): FiltrarDatos> on 2023-05-03 00:00:00+00:00
[2023-05-02T22:10:51.877-0300] {standard_task_runner.py:55} INFO - Started process 1200 to run task
[2023-05-02T22:10:51.898-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'bigdata_tp', 'FiltrarDatos', 'scheduled__2023-05-03T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpw_kp_n1z']
[2023-05-02T22:10:51.907-0300] {standard_task_runner.py:83} INFO - Job 19: Subtask FiltrarDatos
[2023-05-02T22:10:52.057-0300] {task_command.py:389} INFO - Running <TaskInstance: bigdata_tp.FiltrarDatos scheduled__2023-05-03T00:00:00+00:00 [running]> on host DESKTOP-02TA80M.localdomain
[2023-05-02T22:10:52.188-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bigdata_tp
AIRFLOW_CTX_TASK_ID=FiltrarDatos
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-03T00:00:00+00:00
[2023-05-02T22:10:52.190-0300] {dag.py:21} INFO - Levantando ids activos...
[2023-05-02T22:10:52.214-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alanmatys/airflow/dags/dag.py", line 25, in FiltrarDatos
    ads_views = pd.read_csv('~/airflow/data/raw/adv_views.csv').isin(ads_ids['advertiser_id'])
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/alanmatys/airflow/data/raw/adv_views.csv'
[2023-05-02T22:10:52.236-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=bigdata_tp, task_id=FiltrarDatos, execution_date=20230503T000000, start_date=20230503T011051, end_date=20230503T011052
[2023-05-02T22:10:52.262-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 19 for task FiltrarDatos ((sqlite3.OperationalError) disk I/O error
(Background on this error at: https://sqlalche.me/e/14/e3q8); 1200)
[2023-05-02T22:10:52.268-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-02T22:10:52.309-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-02T22:11:23.424-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bigdata_tp.FiltrarDatos scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-02T22:11:23.436-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bigdata_tp.FiltrarDatos scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-02T22:11:23.436-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T22:11:23.436-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-02T22:11:23.436-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-02T22:11:23.456-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): FiltrarDatos> on 2023-05-03 00:00:00+00:00
[2023-05-02T22:11:23.483-0300] {standard_task_runner.py:55} INFO - Started process 1211 to run task
[2023-05-02T22:11:23.496-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'bigdata_tp', 'FiltrarDatos', 'scheduled__2023-05-03T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmptkgk_fvv']
[2023-05-02T22:11:23.502-0300] {standard_task_runner.py:83} INFO - Job 20: Subtask FiltrarDatos
[2023-05-02T22:11:23.593-0300] {task_command.py:389} INFO - Running <TaskInstance: bigdata_tp.FiltrarDatos scheduled__2023-05-03T00:00:00+00:00 [running]> on host DESKTOP-02TA80M.localdomain
[2023-05-02T22:11:23.671-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bigdata_tp
AIRFLOW_CTX_TASK_ID=FiltrarDatos
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-03T00:00:00+00:00
[2023-05-02T22:11:23.672-0300] {dag.py:21} INFO - Levantando ids activos...
[2023-05-02T22:11:23.687-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alanmatys/airflow/dags/dag.py", line 25, in FiltrarDatos
    ads_views = pd.read_csv('~/airflow/data/raw/adv_views.csv').isin(ads_ids['advertiser_id'])
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/alanmatys/airflow_env/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/alanmatys/airflow/data/raw/adv_views.csv'
[2023-05-02T22:11:23.697-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=bigdata_tp, task_id=FiltrarDatos, execution_date=20230503T000000, start_date=20230503T011123, end_date=20230503T011123
[2023-05-02T22:11:23.719-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 20 for task FiltrarDatos ([Errno 2] No such file or directory: '/home/alanmatys/airflow/data/raw/adv_views.csv'; 1211)
[2023-05-02T22:11:23.747-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-02T22:11:23.771-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
